// projects/quick-demo-svelte/src/App.svelte
<script lang="ts">
  import type {
    IAgoraRTCClient,
    IAgoraRTCRemoteUser,
    ICameraVideoTrack,
    IMicrophoneAudioTrack,
  } from "agora-rtc-sdk-ng";

  import AgoraRTC from "agora-rtc-sdk-ng";

  let track: ICameraVideoTrack;
  let audioTrack: IMicrophoneAudioTrack;
  let client: IAgoraRTCClient;

  let isJoined = false;
  let isAudioPubed = false;
  let isVideoPubed = false;
  let isAudioSubed = false;
  let isVideoSubed = false;

  let isVideoOn = false;
  let isAudioOn = false;

  async function turnOnCamera() {
    isVideoOn = !isVideoOn;

    if (track) {
      return track.setEnabled(!track.enabled);
    }
    track = await AgoraRTC.createCameraVideoTrack();
    track.play("camera-video");
  }

  async function turnOnMicrophone() {
    isAudioOn = !isAudioOn;

    if (audioTrack) {
      return audioTrack.setEnabled(!audioTrack.enabled);
    }

    audioTrack = await AgoraRTC.createMicrophoneAudioTrack();
    // audioTrack.play();
  }

  let channel = "";
  // you can apply appid follow the guide https://www.agora.io/en/blog/how-to-get-started-with-agora/
  const APP_ID = "xxxx*****************xxxx";

  async function joinChannel() {
    if (!channel) {
      channel = "svelte-room";
    }

    if (isJoined) {
      await leaveChannel();
    }

    if (!client) {
      client = AgoraRTC.createClient({
        mode: "rtc",
        codec: "vp8",
      });

      client.on("user-published", onUserPublish);
    }

    await client.join(APP_ID, channel, null, null);

    isJoined = true;
  }

  async function leaveChannel() {
    isJoined = false;
    isAudioPubed = false;
    isVideoPubed = false;

    client && (await client.leave());
  }

  async function onUserPublish(
    user: IAgoraRTCRemoteUser,
    mediaType: "video" | "audio"
  ) {
    if (mediaType === "video") {
      const remoteTrack = await client.subscribe(user, mediaType);
      remoteTrack.play("remote-video");
      isVideoSubed = true;
    }
    if (mediaType === "audio") {
      const remoteTrack = await client.subscribe(user, mediaType);
      remoteTrack.play();
      isAudioSubed = true;
    }
  }

  async function publishVideo() {
    if (!isVideoOn) {
      await turnOnCamera();
    }

    if (!isJoined) {
      await joinChannel();
    }
    await client.publish(track);
    isVideoPubed = true;
  }

  async function publishAudio() {
    if (!isAudioOn) {
      await turnOnMicrophone();
    }
    if (!isJoined) {
      await joinChannel();
    }

    await client.publish(audioTrack);
    isAudioPubed = true;
  }
</script>

<div class="left-side">
  <h3>Pleat check you camera / microphone!</h3>
  <div class="buttons">
    <button on:click={turnOnCamera} class={isVideoOn ? "button-on" : ""}>
      Turn {isVideoOn ? "off" : "on"} camera
    </button>
    <button on:click={turnOnMicrophone} class={isAudioOn ? "button-on" : ""}>
      Turn {isAudioOn ? "off" : "on"} Microphone
    </button>
  </div>
  <h3>Please input the channel name</h3>
  <input bind:value={channel} />
  <div class="buttons">
    <button on:click={joinChannel} class={isJoined ? "button-on" : ""}>
      Join Channel
    </button>
    <button on:click={publishVideo} class={isVideoPubed ? "button-on" : ""}>
      Publish Video
    </button>
    <button on:click={publishAudio} class={isAudioPubed ? "button-on" : ""}>
      Publish Audio
    </button>
    <button on:click={leaveChannel}>Leave Channel</button>
  </div>
</div>
<div class="right-side">
  <video id="camera-video">
    <track kind="captions" />
  </video>
  <video id="remote-video">
    <track kind="captions" />
  </video>

  {#if isJoined && !isVideoSubed}
    <div class="waiting">
      You can shared channel {channel} to others.....
    </div>
  {/if}
</div>

<style>
</style>

// projects/quick-demo-react/src/App.tsx
import { useRef, useState } from "react";
import "./App.css";
import AgoraRTC, {
  ICameraVideoTrack,
  IMicrophoneAudioTrack,
  IAgoraRTCClient,
  IAgoraRTCRemoteUser,
} from "agora-rtc-sdk-ng";

const client: IAgoraRTCClient = AgoraRTC.createClient({
  mode: "rtc",
  codec: "vp8",
});
let audioTrack: IMicrophoneAudioTrack;
let videoTrack: ICameraVideoTrack;
function App() {
  const [isAudioOn, setIsAudioOn] = useState(false);
  const [isVideoOn, setIsVideoOn] = useState(false);
  const [isAudioPubed, setIsAudioPubed] = useState(false);
  const [isVideoPubed, setIsVideoPubed] = useState(false);
  const [isVideoSubed, setIsVideoSubed] = useState(false);

  const turnOnCamera = async (flag?: boolean) => {
    flag = flag ?? !isVideoOn;
    setIsVideoOn(flag);

    if (videoTrack) {
      return videoTrack.setEnabled(flag);
    }
    videoTrack = await AgoraRTC.createCameraVideoTrack();
    videoTrack.play("camera-video");
  };

  const turnOnMicrophone = async (flag?: boolean) => {
    flag = flag ?? !isAudioOn;
    setIsAudioOn(flag);

    if (audioTrack) {
      return audioTrack.setEnabled(flag);
    }

    audioTrack = await AgoraRTC.createMicrophoneAudioTrack();
    // audioTrack.play();
  };

  const [isJoined, setIsJoined] = useState(false);
  const channel = useRef("");
  // you can apply appid follow the guide https://www.agora.io/en/blog/how-to-get-started-with-agora/
  const appid = useRef("");
  // you can apply token follow the guide https://www.agora.io/en/blog/how-to-get-started-with-agora/
  const token = useRef("");

  const joinChannel = async () => {
    if (!channel.current) {
      channel.current = "react-room";
    }

    if (isJoined) {
      await leaveChannel();
    }

    client.on("user-published", onUserPublish);

    await client.join(
      appid.current,
      channel.current,
      token.current || null,
      null
    );
    setIsJoined(true);
  };

  const leaveChannel = async () => {
    setIsJoined(false);
    setIsAudioPubed(false);
    setIsVideoPubed(false);

    await client.leave();
  };

  const onUserPublish = async (
    user: IAgoraRTCRemoteUser,
    mediaType: "video" | "audio"
  ) => {
    if (mediaType === "video") {
      const remoteTrack = await client.subscribe(user, mediaType);
      remoteTrack.play("remote-video");
      setIsVideoSubed(true);
    }
    if (mediaType === "audio") {
      const remoteTrack = await client.subscribe(user, mediaType);
      remoteTrack.play();
    }
  };

  const publishVideo = async () => {
    await turnOnCamera(true);

    if (!isJoined) {
      await joinChannel();
    }
    await client.publish(videoTrack);
    setIsVideoPubed(true);
  };

  const publishAudio = async () => {
    await turnOnMicrophone(true);

    if (!isJoined) {
      await joinChannel();
    }

    await client.publish(audioTrack);
    setIsAudioPubed(true);
  };

  return (
    <>
      <div className="left-side">
        <h3>Pleat check you camera / microphone!</h3>
        <div className="buttons">
          <button
            onClick={() => turnOnCamera()}
            className={isVideoOn ? "button-on" : ""}
          >
            Turn {isVideoOn ? "off" : "on"} camera
          </button>
          <button
            onClick={() => turnOnMicrophone()}
            className={isAudioOn ? "button-on" : ""}
          >
            Turn {isAudioOn ? "off" : "on"} Microphone
          </button>
        </div>
        <h3>
          {`Please input the appid and token (`}
          <a href="https://www.agora.io/en/blog/how-to-get-started-with-agora">
            Create an account.
          </a>
          {`) `}
        </h3>
        <input
          defaultValue={appid.current}
          placeholder="appid"
          onChange={(e) => (appid.current = e.target.value)}
        />
        <input
          defaultValue={token.current}
          placeholder="token"
          onChange={(e) => (token.current = e.target.value)}
        />
        <h3>Please input the channel name</h3>
        <input
          defaultValue={channel.current}
          onChange={(e) => (channel.current = e.target.value)}
        />
        <div className="buttons">
          <button onClick={joinChannel} className={isJoined ? "button-on" : ""}>
            Join Channel
          </button>
          <button
            onClick={publishVideo}
            className={isVideoPubed ? "button-on" : ""}
          >
            Publish Video
          </button>
          <button
            onClick={publishAudio}
            className={isAudioPubed ? "button-on" : ""}
          >
            Publish Audio
          </button>
          <button onClick={leaveChannel}>Leave Channel</button>
        </div>
      </div>
      <div className="right-side">
        <video id="camera-video" hidden={isVideoOn ? false : true}></video>
        <video id="remote-video" hidden={isVideoSubed ? false : true}></video>
        {isJoined && !isVideoSubed ? (
          <div className="waiting">
            You can shared channel {channel.current} to others.....
          </div>
        ) : null}
      </div>
    </>
  );
}

export default App;
